# /etc/ansible/roles/common/tasks/create_test-repo-structure.yml
# This playbook creates necessary folders and files on windows
- name: "Creates all necessary folders and files for jenkins and Test frameworks"
  hosts: all
  tasks:
  - name: Create temp directory
    win_file:
      path: C:\temp
      state: directory
  - name: Create Jenkins directory structure
    win_file:
      path: C:\Jenkins
      state: directory
  - name: Create license directory
    win_file:
      path: C:\license
      state: directory
  - name: Create script directory
    win_file:
      path: C:\scripts
      state: directory
  - name: Copy license to remote win host
    win_copy:
      src: /etc/ansible/roles/common/files/windows/license.xml
      dest: C:\license
  - name: Create testsuite unittestframework folder
    win_file:
      path: C:\Jenkins\test_or
      state: directory
  - name: Create Testcomplete folder
    win_file:
      path: C:\Jenkins\TC14_testing_workspace
      state: directory
  - name: Create TC subfolder 32
    win_file:
      path: C:\Jenkins\TC14_testing_workspace\32
      state: directory
  - name: Create TC subfolder 64
    win_file:
      path: C:\Jenkins\TC14_testing_workspace\64
      state: directory
  - name: Create TC subfolder daily_staging
    win_file:
      path: C:\Jenkins\TC14_testing_workspace\daily_staging
      state: directory
  - name: Create TC_Jenkins repo folder
    win_file:
      path: C:\Jenkins\TC14_testing_workspace\TC_Jenkins
      state: directory
  - name: Create TC14_Project repo folder
    win_file:
      path: C:\Jenkins\TC14_testing_workspace\TC14_Project
      state: directory
  - name: Copy jenkin files to TC14_testing_workspace
    win_copy:
      src: /etc/ansible/roles/common/files/windows/TC/
      dest: C:\Jenkins\TC14_testing_workspace
  - name: Create workspace directory for jenkins
    win_file:
      path: C:\Jenkins\workspace
      state: directory
