# /etc/ansible/roles/common/tasks/install-git.yml
# This file installs a git version that is required on windows
- name: "Install git if not installed for windows"
  hosts: all
  gather_facts: false

  vars:
    envpath: "{{ lookup('file', '/etc/ansible/roles/common/vars/external_vars.yml') | from_yaml }}"

  tasks:
  - name: Debug envpath
    debug:
      msg: "{{ item.value }}"
    with_dict: "{{ envpath }}"

  - name: Print only the envpath for git
    debug:
      msg: "{{ lookup('items', item.winenvpath.git_path) }}"
    with_items: "{{ envpath }}"

  - name: Determine if git is installed
    win_command: git --version
    register: validateinstaller
    ignore_errors: true
#    when: 'is not recognized' in validatecygcheck.stderr

  - name: Print previous step result
    debug:
      var: validateinstaller
      verbosity: 2

  - name: States the git installations
    debug:
      msg: "{{ validateinstaller.stdout }} is already installed"
    when: validateinstaller.rc == 0

  - name: Downloads the git installer
    win_get_url:
      url: "{{ item.windloadpath.git_dpath }}"
      dest: 'C:\temp\{{ item.winfilenm.git_flnm }}'
    with_items: "{{ envpath }}"
    when: validateinstaller.rc == 2

  - name: Installs git on remote windows
    raw: 'C:\temp\{{ item.winfilenm.git_flnm }} /VERYSILENT /NORESTART'
    with_items: "{{ envpath }}"
    become: true
    become_method: runas
    become_user: Administrator
    when: validateinstaller.rc == 2

  - name: Determine if git is added to PATH
    win_shell: |
      $Env:Path
    register: validatepath

  - name: Print previous step result
    debug:
      var: validatepath
      verbosity: 2

  - name: Append new value to PATH
    win_environment:
      name: path
      value: "{{ validatepath.stdout | regex_replace('[\r\n]*', '') + ';' + item.winenvpath.git_path }}"
      state: present
      level: machine
    with_items: "{{ envpath }}"
    when: not 'Git' in validatepath.stdout

  - include: /etc/ansible/roles/common/handlers/rm_duplicate_winenvs.yml

    #  - name: "Restart Windows"
    #    win_reboot:
